<%@ page import="org.apache.xmlrpc.*,org.put.snippetreader.*,org.put.util.text.HtmlHelper,gnu.regexp.*,java.util.*"
         session="false"
         contentType="text/html; charset=utf-8"
%>
<html>
        <jsp:include page="top.jsp" flush="true" />

	<h1>XMLRPC Services</h1>
        <p>
        Listed below are the services currently available in this instance of SnippetReader. Each service
        contains a number of methods, all of them can be invoked using XmlRpc protocol. Please note that
        because SnippetReader is implemented in Java, methods are listed using Java data types - these must be
        mapped to XmlRpc using the following rules:
        <p>
        <TABLE>
            <TR>
                <TD bgcolor="#a0ddf0" colspan="" rowspan="" valign="top" align="left"><FONT color="#000000" size="-1" face="arial,helvetica,sanserif">
                    <B>XML-RPC data type</B>
                </FONT>
                </TD>
                <TD bgcolor="#a0ddf0" colspan="" rowspan="" valign="top" align="left"><FONT color="#000000" size="-1" face="arial,helvetica,sanserif">
                    <B>Data Types generated by the Parser</B>
                </FONT>
                </TD>
                <TD bgcolor="#a0ddf0" colspan="" rowspan="" valign="top" align="left"><FONT color="#000000" size="-1" face="arial,helvetica,sanserif">
                    <B>Types expected by the Invoker as input parameters of RPC handlers</B>
                </FONT>
                </TD>
            </TR>
            <TR>
                <TD bgcolor="#a0ddf0" colspan="" rowspan="" valign="top" align="left"><FONT color="#000000" size="-1" face="arial,helvetica,sanserif">
                    &lt;i4&gt; or &lt;int&gt;
                </FONT>
                </TD>
                <TD bgcolor="#a0ddf0" colspan="" rowspan="" valign="top" align="left"><FONT color="#000000" size="-1" face="arial,helvetica,sanserif">
                    java.lang.Integer
                </FONT>
                </TD>
                <TD bgcolor="#a0ddf0" colspan="" rowspan="" valign="top" align="left"><FONT color="#000000" size="-1" face="arial,helvetica,sanserif">
                    <FONT color="#000000">int</FONT>
                </FONT>
                </TD>
            </TR>
            <TR>
                <TD bgcolor="#a0ddf0" colspan="" rowspan="" valign="top" align="left"><FONT color="#000000" size="-1" face="arial,helvetica,sanserif">
                    &lt;boolean&gt;
                </FONT>
                </TD>
                <TD bgcolor="#a0ddf0" colspan="" rowspan="" valign="top" align="left"><FONT color="#000000" size="-1" face="arial,helvetica,sanserif">
                    java.lang.Boolean
                </FONT>
                </TD>
                <TD bgcolor="#a0ddf0" colspan="" rowspan="" valign="top" align="left"><FONT color="#000000" size="-1" face="arial,helvetica,sanserif">
                    <FONT color="#000000">boolean</FONT>
                </FONT>
                </TD>
            </TR>
            <TR>
                <TD bgcolor="#a0ddf0" colspan="" rowspan="" valign="top" align="left"><FONT color="#000000" size="-1" face="arial,helvetica,sanserif">
                    &lt;string&gt;
                </FONT>
                </TD>
                <TD bgcolor="#a0ddf0" colspan="" rowspan="" valign="top" align="left"><FONT color="#000000" size="-1" face="arial,helvetica,sanserif">
                    java.lang.String
                </FONT>
                </TD>
                <TD bgcolor="#a0ddf0" colspan="" rowspan="" valign="top" align="left"><FONT color="#000000" size="-1" face="arial,helvetica,sanserif">
                    java.lang.String
                </FONT>
                </TD>
            </TR>
            <TR>
                <TD bgcolor="#a0ddf0" colspan="" rowspan="" valign="top" align="left"><FONT color="#000000" size="-1" face="arial,helvetica,sanserif">
                    &lt;double&gt;
                </FONT>
                </TD>
                <TD bgcolor="#a0ddf0" colspan="" rowspan="" valign="top" align="left"><FONT color="#000000" size="-1" face="arial,helvetica,sanserif">
                    java.lang.Double
                </FONT>
                </TD>
                <TD bgcolor="#a0ddf0" colspan="" rowspan="" valign="top" align="left"><FONT color="#000000" size="-1" face="arial,helvetica,sanserif">
                    <FONT color="#000000">double</FONT>
                </FONT>
                </TD>
            </TR>
            <TR>
                <TD bgcolor="#a0ddf0" colspan="" rowspan="" valign="top" align="left"><FONT color="#000000" size="-1" face="arial,helvetica,sanserif">
                    &lt;dateTime.iso8601&gt;
                </FONT>
                </TD>
                <TD bgcolor="#a0ddf0" colspan="" rowspan="" valign="top" align="left"><FONT color="#000000" size="-1" face="arial,helvetica,sanserif">
                    java.util.Date
                </FONT>
                </TD>
                <TD bgcolor="#a0ddf0" colspan="" rowspan="" valign="top" align="left"><FONT color="#000000" size="-1" face="arial,helvetica,sanserif">
                    java.util.Date
                </FONT>
                </TD>
            </TR>
            <TR>
                <TD bgcolor="#a0ddf0" colspan="" rowspan="" valign="top" align="left"><FONT color="#000000" size="-1" face="arial,helvetica,sanserif">
                    &lt;struct&gt;
                </FONT>
                </TD>
                <TD bgcolor="#a0ddf0" colspan="" rowspan="" valign="top" align="left"><FONT color="#000000" size="-1" face="arial,helvetica,sanserif">
                    java.util.Hashtable
                </FONT>
                </TD>
                <TD bgcolor="#a0ddf0" colspan="" rowspan="" valign="top" align="left"><FONT color="#000000" size="-1" face="arial,helvetica,sanserif">
                    java.util.Hashtable
                </FONT>
                </TD>
            </TR>
            <TR>
                <TD bgcolor="#a0ddf0" colspan="" rowspan="" valign="top" align="left"><FONT color="#000000" size="-1" face="arial,helvetica,sanserif">
                    &lt;array&gt;
                </FONT>
                </TD>
                <TD bgcolor="#a0ddf0" colspan="" rowspan="" valign="top" align="left"><FONT color="#000000" size="-1" face="arial,helvetica,sanserif">
                    java.util.Vector
                </FONT>
                </TD>
                <TD bgcolor="#a0ddf0" colspan="" rowspan="" valign="top" align="left"><FONT color="#000000" size="-1" face="arial,helvetica,sanserif">
                    java.util.Vector
                </FONT>
                </TD>
            </TR>
            <TR>
                <TD bgcolor="#a0ddf0" colspan="" rowspan="" valign="top" align="left"><FONT color="#000000" size="-1" face="arial,helvetica,sanserif">
                    &lt;base64&gt;
                </FONT>
                </TD>
                <TD bgcolor="#a0ddf0" colspan="" rowspan="" valign="top" align="left"><FONT color="#000000" size="-1" face="arial,helvetica,sanserif">
                    byte[ ]
                </FONT>
                </TD>
                <TD bgcolor="#a0ddf0" colspan="" rowspan="" valign="top" align="left"><FONT color="#000000" size="-1" face="arial,helvetica,sanserif">
                    byte[ ]
                </FONT>
                </TD>
            </TR>
        </TABLE>
        <p>

        <h1>List of registered XMLRPC services</h1>
        <ol>
        <%
            XmlRpcClientLite client = new XmlRpcClientLite( org.put.snippetreader.XmlRpcServlet.getSnippetReaderServiceURL(request));
            Vector services = (Vector) client.execute("_meta.getVerboseServicesList", new Vector());

            for (int i=0;i<services.size();i++)
            {
                Hashtable s = (Hashtable) services.elementAt(i);

                String service = (String) s.get("name");

                %>
                <h3><li><%= service %></li></h3>
                <blockquote>
                    <table border="1" cellspacing=1 cellpadding=1>
                    <tr><th>Property name</th><th>Value</th></tr>
                        <%
                        SortedSet ss = new TreeSet( s.keySet() );
                        for (Iterator e = ss.iterator(); e.hasNext(); )
                        {
                            Object o = e.next();
                            if ("Carrot2".equals(o)) {
                                s.put(o, "Supports Carrot2 under URL: "
                                      + org.put.snippetreader.XmlRpcServlet.getSnippetReaderServiceURL(request)
                                      + "/carrot2/" + service);
                            }
                            %><tr><td><b><%= o %></b></td><td><%= s.get(o) %></td></tr><%
                        }
                        %>
                    </table>
                </blockquote>
                <%
            }
        %>
        </ol>
	</body>
</html>