/* Generated By:JavaCC: Do not edit this line. JavaCCWordBasedParserImplConstants.java */
package com.dawidweiss.carrot.util.tokenizer.parser.javacc;

public interface JavaCCWordBasedParserImplConstants {

  int EOF = 0;
  int URL = 1;
  int WWWADDR = 2;
  int URLPATH = 3;
  int TERM = 4;
  int ACRONYM = 5;
  int EMAIL = 6;
  int SENTENCEMARKER = 7;
  int PUNCTUATION = 8;
  int NUMERIC = 9;
  int HYPHTERM = 10;
  int SYMBOL = 11;
  int WHSPACE = 12;
  int LETTERSEQ = 13;
  int LETTER = 14;
  int DIGIT = 15;
  int SPACES = 16;
  int NOISE = 17;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<URL>",
    "<WWWADDR>",
    "<URLPATH>",
    "<TERM>",
    "<ACRONYM>",
    "<EMAIL>",
    "<SENTENCEMARKER>",
    "<PUNCTUATION>",
    "<NUMERIC>",
    "<HYPHTERM>",
    "<SYMBOL>",
    "<WHSPACE>",
    "<LETTERSEQ>",
    "<LETTER>",
    "<DIGIT>",
    "<SPACES>",
    "<NOISE>",
  };

}
