/*
 * Carrot2 Project
 * Copyright (C) 2002-2004, Dawid Weiss
 * All rights reserved.
 *
 * Refer to full text of the license "carrot2.LICENSE" in the root folder
 * of CVS checkout or at:
 * http://www.cs.put.poznan.pl/dweiss/carrot2.LICENSE
 */

/* Generated By:JavaCC: Do not edit this line. TokenizerImplConstants.java */
package com.dawidweiss.carrot.tokenizer;


public interface TokenizerImplConstants
{
    int EOF = 0;
    int URL = 1;
    int WWWADDR = 2;
    int URLPATH = 3;
    int TERM = 4;
    int HYPHTERM = 5;
    int PERSON = 6;
    int ACRONYM = 7;
    int EMAIL = 8;
    int SENTENCEMARKER = 9;
    int PUNCTUATION = 10;
    int NUMERIC = 11;
    int SYMBOL = 12;
    int WHSPACE = 13;
    int LETTERSEQ = 14;
    int LETTER = 15;
    int DIGIT = 16;
    int SPACES = 17;
    int NOISE = 18;
    int DEFAULT = 0;
    String [] tokenImage = 
    {
        "<EOF>", "<URL>", "<WWWADDR>", "<URLPATH>", "<TERM>", "<HYPHTERM>", "<PERSON>", "<ACRONYM>",
        "<EMAIL>", "<SENTENCEMARKER>", "<PUNCTUATION>", "<NUMERIC>", "<SYMBOL>", "<WHSPACE>",
        "<LETTERSEQ>", "<LETTER>", "<DIGIT>", "<SPACES>", "<NOISE>",
    };
}
