/* Generated By:JavaCC: Do not edit this line. TokenizerImplConstants.java */
package com.chilang.carrot.tokenizer;

public interface TokenizerImplConstants {

  int EOF = 0;
  int URL = 1;
  int URLPATH = 2;
  int TERM = 3;
  int HYPHTERM = 4;
  int PERSON = 5;
  int ACRONYM = 6;
  int EMAIL = 7;
  int SENTENCEMARKER = 8;
  int PHRASEMARKER = 9;
  int HTMLENTITY = 10;
  int SYMBOL = 11;
  int WHSPACE = 12;
  int LETTERSEQ = 13;
  int LETTER = 14;
  int DIGIT = 15;
  int SPACES = 16;
  int NOISE = 17;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<URL>",
    "<URLPATH>",
    "<TERM>",
    "<HYPHTERM>",
    "<PERSON>",
    "<ACRONYM>",
    "<EMAIL>",
    "<SENTENCEMARKER>",
    "<PHRASEMARKER>",
    "<HTMLENTITY>",
    "<SYMBOL>",
    "<WHSPACE>",
    "<LETTERSEQ>",
    "<LETTER>",
    "<DIGIT>",
    "<SPACES>",
    "<NOISE>",
  };

}
