

/*
 * Carrot2 Project
 * Copyright (C) 2002-2003, Dawid Weiss
 * Portions (C) Contributors listen in carrot2.CONTRIBUTORS file.
 * All rights reserved.
 * 
 * Refer to full text of the licence "carrot2.LICENCE" in the root folder
 * of CVS checkout or at: 
 * http://www.cs.put.poznan.pl/dweiss/carrot2.LICENCE
 */


/* Generated By:JavaCC: Do not edit this line. TokenizerImplConstants.java */
package com.dawidweiss.carrot.tokenizer;


public interface TokenizerImplConstants
{
    int EOF = 0;
    int URL = 1;
    int URLPATH = 2;
    int TERM = 3;
    int HYPHTERM = 4;
    int PERSON = 5;
    int ACRONYM = 6;
    int EMAIL = 7;
    int SENTENCEMARKER = 8;
    int SYMBOL = 9;
    int WHSPACE = 10;
    int LETTERSEQ = 11;
    int LETTER = 12;
    int DIGIT = 13;
    int SPACES = 14;
    int NOISE = 15;
    int DEFAULT = 0;
    String [] tokenImage = 
    {
        "<EOF>", "<URL>", "<URLPATH>", "<TERM>", "<HYPHTERM>", "<PERSON>", "<ACRONYM>", "<EMAIL>",
        "<SENTENCEMARKER>", "<SYMBOL>", "<WHSPACE>", "<LETTERSEQ>", "<LETTER>", "<DIGIT>",
        "<SPACES>", "<NOISE>",
    };
}
