package org.carrot2.webapp.model;

import java.util.List;

import javax.servlet.http.HttpServletRequest;

import org.carrot2.webapp.jawr.JawrUrlGenerator;
import org.simpleframework.xml.ElementList;

/**
 * Contains URLs for CSS and JS generated by Jawr.
 */
public class AssetUrlsModel
{
    @ElementList(name = "css-urls", entry = "css-url")
    public final List<String> cssUrls;

    @ElementList(name = "js-urls", entry = "js-url")
    public final List<String> jsUrls;

    public AssetUrlsModel(String skinId, HttpServletRequest request,
        JawrUrlGenerator generator)
    {
        this.cssUrls = generator.getCssUrls(request, "/" + skinId + ".jcss");
        this.jsUrls = generator.getJsUrls(request, "/" + skinId + ".jjs");
    }
}
