// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/main/jflex/org/carrot2/language/ExtendedWhitespaceTokenizerImpl.jflex

package org.carrot2.language;

/** JFlex-generated scanner. */

@SuppressWarnings("fallthrough")
public final class ExtendedWhitespaceTokenizerImpl {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\5\u0100\1\u0200\2\u0100\1\u0300\1\u0400\1\u0500\1\u0400"+
    "\1\u0600\1\u0700\1\u0100\1\u0800\17\u0100\1\u0900\17\u0a00\1\u0b00"+
    "\1\u0c00\1\u0a00\1\u0d00\11\u0100\1\u0e00\20\u0a00\122\u0100\14\u0a00"+
    "\53\u0100\1\u0f00\10\u1000\31\u0a00\2\u0100\u1005\u0a00";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\12\0\1\1\2\0\1\2\23\0\1\3\1\0\1\4"+
    "\2\5\1\6\1\7\4\5\1\10\1\11\1\12\1\13"+
    "\12\14\1\15\1\16\1\0\1\5\1\0\1\3\1\17"+
    "\32\20\1\5\1\0\1\5\1\0\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\2\20\1\34\1\35\1\36\1\37\1\40\1\20\1\41"+
    "\1\42\1\43\1\44\1\45\3\20\1\46\3\0\1\5"+
    "\70\0\1\47\10\0\27\50\1\0\37\50\1\0\u0168\50"+
    "\12\51\206\50\12\51\152\50\2\47\12\51\166\50\12\51"+
    "\166\50\12\51\166\50\12\51\166\50\12\51\167\50\11\51"+
    "\166\50\12\51\340\50\12\51\166\50\12\51\146\50\12\51"+
    "\266\50\u0240\0\u0150\50\160\0\200\50\200\0\56\50\322\0"+
    "\244\50\134\0\u0100\52";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\2\1\1\2\1\1\1\3\1\4\4\5\1\4"+
    "\2\0\1\6\2\0\1\5\1\6\1\4\2\0\1\6"+
    "\5\5\1\6\1\5\1\7\1\4\1\0\1\4\12\6"+
    "\1\4\1\10\1\11\1\5\1\12\12\6\4\5\3\4"+
    "\12\13\1\4\2\0\1\5\1\0\1\11\1\0\2\5"+
    "\1\11\1\14\1\6\2\14\2\6\1\14\1\6\1\14"+
    "\1\12\1\0\2\5\12\6\1\10\2\4\1\0\1\5"+
    "\5\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[119];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\53\0\126\0\201\0\254\0\53\0\327\0\u0102"+
    "\0\u012d\0\u0158\0\u0183\0\u01ae\0\u01d9\0\u0204\0\u022f\0\u025a"+
    "\0\u0285\0\u02b0\0\u02db\0\u0306\0\u0331\0\u035c\0\u0387\0\u03b2"+
    "\0\u03dd\0\u0408\0\u0433\0\u045e\0\u0489\0\u04b4\0\53\0\u04df"+
    "\0\u050a\0\u0535\0\u0560\0\u058b\0\u05b6\0\u05e1\0\u060c\0\u0637"+
    "\0\u0662\0\u068d\0\u06b8\0\u06e3\0\u070e\0\u0739\0\u0764\0\u078f"+
    "\0\u07ba\0\u07e5\0\u0810\0\u083b\0\u0866\0\u0891\0\u08bc\0\u08e7"+
    "\0\u0912\0\u093d\0\u0968\0\u035c\0\u0993\0\u09be\0\u09e9\0\u0a14"+
    "\0\u0a3f\0\u0a6a\0\u0a95\0\u0ac0\0\u0aeb\0\u0b16\0\u0b41\0\u0b6c"+
    "\0\u0b97\0\u0bc2\0\u0bed\0\u0c18\0\u0c43\0\u0c6e\0\u0c99\0\u0cc4"+
    "\0\u0cef\0\u03b2\0\u0d1a\0\u0d45\0\u0d70\0\u04b4\0\u0d9b\0\u0a95"+
    "\0\u0dc6\0\u0df1\0\u0e1c\0\u0e47\0\u0e72\0\u0e9d\0\u0ec8\0\u0ef3"+
    "\0\u0f1e\0\u0f49\0\u0f74\0\u0f9f\0\u0fca\0\u0ff5\0\u1020\0\u104b"+
    "\0\u1076\0\u10a1\0\u10cc\0\u10f7\0\u1122\0\u114d\0\u1178\0\u11a3"+
    "\0\u11ce\0\u11f9\0\u1224\0\u124f\0\u127a\0\u12a5\0\u12d0";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[119];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\2\2\1\3\1\4\2\2\1\5\3\6\1\4\1\2"+
    "\1\7\1\6\1\4\1\2\1\10\1\2\1\6\5\10"+
    "\1\11\1\10\1\12\2\10\1\13\11\10\1\4\1\10"+
    "\1\14\55\0\1\2\54\0\1\4\6\0\1\4\3\0"+
    "\1\4\30\0\1\4\7\0\1\15\7\0\1\15\3\0"+
    "\1\15\2\0\24\15\14\0\1\16\1\17\1\20\1\16"+
    "\1\7\1\16\1\0\1\21\1\22\1\23\1\0\24\22"+
    "\1\0\1\22\1\24\7\0\1\25\1\26\1\0\1\27"+
    "\1\30\1\0\1\22\2\0\1\21\1\22\1\23\1\26"+
    "\17\22\1\31\4\22\1\0\2\22\7\0\1\25\1\26"+
    "\1\0\1\27\1\30\1\0\1\22\2\0\1\21\1\22"+
    "\1\23\1\26\17\22\1\31\1\32\3\22\1\0\2\22"+
    "\7\0\1\25\1\26\1\0\1\27\1\30\1\0\1\22"+
    "\2\0\1\21\1\22\1\23\1\26\17\22\1\31\1\33"+
    "\3\22\1\0\2\22\7\0\1\25\1\26\1\0\1\27"+
    "\1\30\1\0\1\22\2\0\1\21\1\22\1\23\1\26"+
    "\1\34\16\22\1\31\4\22\1\0\2\22\7\0\1\25"+
    "\1\26\1\16\1\35\1\36\1\16\1\24\1\16\1\0"+
    "\1\21\1\22\1\23\1\26\17\22\1\31\4\22\1\0"+
    "\1\22\1\24\5\0\1\15\7\0\1\15\1\0\1\37"+
    "\1\0\1\15\2\0\24\15\20\0\1\40\34\0\1\40"+
    "\12\0\1\23\1\41\1\0\1\42\2\0\1\21\2\23"+
    "\1\0\24\23\1\0\1\23\1\42\15\0\1\42\3\0"+
    "\1\43\2\0\1\44\1\45\1\46\1\43\1\47\1\43"+
    "\1\50\1\43\1\51\1\43\1\52\1\53\1\54\7\43"+
    "\1\0\1\43\1\55\15\0\1\56\3\0\1\56\2\0"+
    "\24\56\1\0\2\56\7\0\1\25\1\26\1\0\1\27"+
    "\1\41\1\0\1\22\2\0\1\21\1\22\1\23\1\26"+
    "\17\22\1\31\4\22\1\0\2\22\12\0\1\23\1\41"+
    "\1\0\1\23\2\0\1\21\2\23\1\0\24\23\1\0"+
    "\2\23\7\0\1\25\1\26\1\16\1\35\1\20\1\16"+
    "\1\24\1\16\1\0\1\21\1\22\1\23\1\26\17\22"+
    "\1\31\4\22\1\0\1\22\1\24\15\0\1\25\3\0"+
    "\1\57\2\0\24\57\1\0\2\57\21\0\1\60\2\0"+
    "\24\60\1\0\2\60\12\0\1\23\1\41\1\0\1\27"+
    "\2\0\1\21\1\61\1\23\1\0\24\61\1\0\2\61"+
    "\15\0\1\23\3\0\1\62\2\0\1\63\1\64\1\65"+
    "\1\62\1\66\1\62\1\67\1\62\1\70\1\62\1\71"+
    "\1\72\1\73\7\62\1\0\2\62\7\0\1\25\1\74"+
    "\1\0\1\27\1\41\1\0\1\22\2\0\1\21\1\22"+
    "\1\23\1\74\17\22\1\31\4\22\1\0\2\22\7\0"+
    "\1\25\1\26\1\0\1\27\1\41\1\0\1\22\2\0"+
    "\1\21\1\22\1\23\1\26\15\22\1\75\1\22\1\31"+
    "\4\22\1\0\2\22\7\0\1\25\1\26\1\0\1\27"+
    "\1\41\1\0\1\22\2\0\1\21\1\22\1\23\1\26"+
    "\17\22\1\31\1\76\3\22\1\0\2\22\7\0\1\25"+
    "\1\26\1\0\1\27\1\41\1\0\1\22\2\0\1\21"+
    "\1\22\1\23\1\26\10\22\1\77\6\22\1\31\4\22"+
    "\1\0\2\22\12\0\1\23\1\41\1\0\1\100\2\0"+
    "\1\21\1\61\1\23\1\0\24\61\1\0\1\61\1\101"+
    "\15\0\1\42\3\0\1\62\2\0\1\63\1\64\1\65"+
    "\1\62\1\66\1\62\1\67\1\62\1\70\1\62\1\71"+
    "\1\72\1\73\7\62\1\0\1\62\1\102\11\0\4\16"+
    "\1\40\1\16\33\0\1\40\15\0\1\23\3\0\1\43"+
    "\2\0\1\44\1\45\1\46\1\43\1\47\1\43\1\50"+
    "\1\43\1\51\1\43\1\52\1\53\1\54\7\43\1\0"+
    "\2\43\11\0\1\16\1\17\1\20\1\16\1\42\1\16"+
    "\1\0\1\21\2\23\1\0\24\23\1\0\1\23\1\42"+
    "\12\0\1\23\1\41\1\0\1\23\2\0\1\21\1\103"+
    "\1\23\1\0\24\103\1\0\2\103\12\0\1\23\1\41"+
    "\1\0\1\23\2\0\1\21\1\103\1\23\1\0\16\103"+
    "\1\104\5\103\1\0\2\103\12\0\1\23\1\41\1\0"+
    "\1\23\2\0\1\21\1\103\1\23\1\0\10\103\1\105"+
    "\13\103\1\0\2\103\12\0\1\23\1\41\1\0\1\23"+
    "\2\0\1\21\1\103\1\23\1\0\14\103\1\106\7\103"+
    "\1\0\2\103\12\0\1\23\1\41\1\0\1\23\2\0"+
    "\1\21\1\103\1\23\1\0\3\103\1\107\20\103\1\0"+
    "\2\103\12\0\1\23\1\41\1\0\1\23\2\0\1\21"+
    "\1\103\1\23\1\0\14\103\1\110\7\103\1\0\2\103"+
    "\12\0\1\23\1\41\1\0\1\23\2\0\1\21\1\103"+
    "\1\23\1\0\13\103\1\111\10\103\1\0\2\103\12\0"+
    "\1\23\1\41\1\0\1\23\2\0\1\21\1\103\1\23"+
    "\1\0\10\103\1\112\13\103\1\0\2\103\12\0\1\23"+
    "\1\41\1\0\1\23\2\0\1\21\1\103\1\23\1\0"+
    "\4\103\1\113\17\103\1\0\2\103\12\0\1\23\1\41"+
    "\1\0\1\23\2\0\1\21\1\103\1\23\1\0\16\103"+
    "\1\114\5\103\1\0\2\103\11\0\1\16\1\17\1\20"+
    "\1\16\1\42\1\16\1\0\1\21\1\103\1\23\1\0"+
    "\24\103\1\0\1\103\1\115\12\0\1\56\1\21\1\0"+
    "\1\56\3\0\2\56\1\0\24\56\1\0\2\56\7\0"+
    "\1\25\1\116\4\0\1\57\3\0\1\57\1\0\1\116"+
    "\24\57\1\0\2\57\7\0\1\25\1\26\1\0\1\117"+
    "\2\0\1\60\3\0\1\60\1\0\1\26\17\60\1\120"+
    "\4\60\1\0\2\60\10\0\1\121\1\0\1\27\1\41"+
    "\1\0\1\61\2\0\1\21\1\61\1\23\1\121\24\61"+
    "\1\0\2\61\12\0\1\23\1\122\1\0\1\23\2\0"+
    "\1\21\1\103\1\23\1\0\24\103\1\0\2\103\12\0"+
    "\1\23\1\122\1\0\1\23\2\0\1\21\1\103\1\23"+
    "\1\0\16\103\1\104\5\103\1\0\2\103\12\0\1\23"+
    "\1\122\1\0\1\23\2\0\1\21\1\103\1\23\1\0"+
    "\10\103\1\105\13\103\1\0\2\103\12\0\1\23\1\122"+
    "\1\0\1\23\2\0\1\21\1\103\1\23\1\0\14\103"+
    "\1\106\7\103\1\0\2\103\12\0\1\23\1\122\1\0"+
    "\1\23\2\0\1\21\1\103\1\23\1\0\3\103\1\107"+
    "\20\103\1\0\2\103\12\0\1\23\1\122\1\0\1\23"+
    "\2\0\1\21\1\103\1\23\1\0\14\103\1\110\7\103"+
    "\1\0\2\103\12\0\1\23\1\122\1\0\1\23\2\0"+
    "\1\21\1\103\1\23\1\0\13\103\1\111\10\103\1\0"+
    "\2\103\12\0\1\23\1\122\1\0\1\23\2\0\1\21"+
    "\1\103\1\23\1\0\10\103\1\112\13\103\1\0\2\103"+
    "\12\0\1\23\1\122\1\0\1\23\2\0\1\21\1\103"+
    "\1\23\1\0\4\103\1\113\17\103\1\0\2\103\12\0"+
    "\1\23\1\122\1\0\1\23\2\0\1\21\1\103\1\23"+
    "\1\0\16\103\1\114\5\103\1\0\2\103\7\0\1\25"+
    "\1\26\1\0\1\27\1\41\1\0\1\22\1\123\1\0"+
    "\1\21\1\22\1\23\1\26\17\22\1\31\4\22\1\0"+
    "\2\22\7\0\1\25\1\26\1\0\1\27\1\41\1\0"+
    "\1\22\2\0\1\21\1\22\1\23\1\26\15\22\1\124"+
    "\1\22\1\31\4\22\1\0\2\22\7\0\1\25\1\26"+
    "\1\0\1\27\1\41\1\0\1\22\2\0\1\21\1\22"+
    "\1\23\1\26\11\22\1\125\5\22\1\31\4\22\1\0"+
    "\2\22\11\0\1\16\1\17\1\20\1\16\1\100\1\16"+
    "\1\0\1\21\1\61\1\23\1\0\24\61\1\0\1\61"+
    "\1\101\10\0\1\121\1\16\1\35\1\20\1\16\1\101"+
    "\1\16\1\0\1\21\1\61\1\23\1\121\24\61\1\0"+
    "\1\61\1\101\11\0\1\16\1\17\1\126\1\16\1\42"+
    "\1\16\1\0\1\21\1\103\1\23\1\0\24\103\1\0"+
    "\1\103\1\115\4\0\6\127\1\130\1\131\1\127\1\130"+
    "\2\127\1\132\2\130\1\0\24\130\1\0\2\130\4\0"+
    "\6\127\1\130\1\131\1\127\1\130\2\127\1\132\2\130"+
    "\1\0\15\130\1\133\6\130\1\0\2\130\4\0\6\127"+
    "\1\130\1\131\1\127\1\130\2\127\1\132\2\130\1\0"+
    "\23\130\1\103\1\0\2\130\4\0\6\127\1\130\1\131"+
    "\1\127\1\130\2\127\1\132\2\130\1\0\12\130\1\103"+
    "\11\130\1\0\2\130\4\0\6\127\1\130\1\131\1\127"+
    "\1\130\2\127\1\132\2\130\1\0\21\130\1\103\2\130"+
    "\1\0\2\130\4\0\6\127\1\130\1\131\1\127\1\130"+
    "\2\127\1\132\2\130\1\0\22\130\1\103\1\130\1\0"+
    "\2\130\4\0\6\127\1\130\1\131\1\127\1\130\2\127"+
    "\1\132\2\130\1\0\5\130\1\134\16\130\1\0\2\130"+
    "\4\0\6\127\1\130\1\131\1\127\1\130\2\127\1\132"+
    "\2\130\1\0\11\130\1\103\12\130\1\0\2\130\4\0"+
    "\6\127\1\130\1\131\1\127\1\130\2\127\1\132\2\130"+
    "\1\0\20\130\1\103\3\130\1\0\2\130\4\0\6\127"+
    "\1\130\1\131\1\127\1\130\2\127\1\132\2\130\1\0"+
    "\6\130\1\103\15\130\1\0\2\130\4\0\5\127\1\135"+
    "\1\136\1\137\1\135\1\115\1\135\1\127\1\132\2\130"+
    "\1\0\24\130\1\0\1\130\1\115\21\0\1\57\2\0"+
    "\24\57\1\0\2\57\15\0\1\117\3\0\1\140\2\0"+
    "\24\140\1\0\2\140\7\0\1\25\1\74\1\0\1\117"+
    "\2\0\1\60\3\0\1\60\1\0\1\74\17\60\1\120"+
    "\4\60\1\0\2\60\21\0\1\140\2\0\24\140\1\0"+
    "\2\140\14\0\1\141\45\0\1\25\1\26\1\0\1\27"+
    "\1\41\1\0\1\22\1\123\1\0\1\21\1\22\1\23"+
    "\1\26\17\22\1\142\4\22\1\0\2\22\7\0\1\25"+
    "\1\26\1\0\1\27\1\41\1\0\1\22\2\0\1\21"+
    "\1\22\1\23\1\26\17\22\1\31\1\143\3\22\1\0"+
    "\2\22\4\0\17\127\1\0\24\127\1\0\2\127\4\0"+
    "\11\127\1\130\3\127\1\144\1\127\1\0\1\145\1\146"+
    "\1\147\1\144\1\150\1\144\1\151\1\144\1\152\1\144"+
    "\1\153\1\154\1\155\7\144\1\0\2\144\4\0\11\127"+
    "\1\156\3\127\1\156\1\127\1\0\24\156\1\0\2\156"+
    "\4\0\6\127\1\130\1\131\1\127\1\130\2\127\1\132"+
    "\2\130\1\0\1\103\23\130\1\0\2\130\4\0\6\127"+
    "\1\130\1\131\1\127\1\130\2\127\1\132\2\130\1\0"+
    "\14\130\1\103\7\130\1\0\2\130\4\0\11\127\1\157"+
    "\5\127\1\0\24\127\1\0\1\127\1\157\4\0\6\127"+
    "\1\130\1\131\1\127\1\115\2\127\1\132\2\130\1\0"+
    "\24\130\1\0\1\130\1\115\4\0\11\127\1\115\3\127"+
    "\1\144\1\127\1\0\1\145\1\146\1\147\1\144\1\150"+
    "\1\144\1\151\1\144\1\152\1\144\1\153\1\154\1\155"+
    "\7\144\1\0\1\144\1\160\10\0\1\121\1\0\1\117"+
    "\2\0\1\140\3\0\1\140\1\0\1\121\24\140\1\0"+
    "\2\140\14\0\1\161\45\0\1\25\1\74\1\0\1\27"+
    "\1\41\1\0\1\22\1\123\1\0\1\21\1\22\1\23"+
    "\1\74\17\22\1\31\4\22\1\0\2\22\7\0\1\25"+
    "\1\26\1\0\1\27\1\41\1\0\1\22\2\0\1\21"+
    "\1\22\1\23\1\26\14\22\1\162\2\22\1\31\4\22"+
    "\1\0\2\22\4\0\6\127\1\130\1\131\1\127\1\130"+
    "\2\127\1\132\1\103\1\130\1\0\24\103\1\0\2\103"+
    "\4\0\6\127\1\130\1\131\1\127\1\130\2\127\1\132"+
    "\1\103\1\130\1\0\16\103\1\104\5\103\1\0\2\103"+
    "\4\0\6\127\1\130\1\131\1\127\1\130\2\127\1\132"+
    "\1\103\1\130\1\0\10\103\1\105\13\103\1\0\2\103"+
    "\4\0\6\127\1\130\1\131\1\127\1\130\2\127\1\132"+
    "\1\103\1\130\1\0\14\103\1\106\7\103\1\0\2\103"+
    "\4\0\6\127\1\130\1\131\1\127\1\130\2\127\1\132"+
    "\1\103\1\130\1\0\3\103\1\107\20\103\1\0\2\103"+
    "\4\0\6\127\1\130\1\131\1\127\1\130\2\127\1\132"+
    "\1\103\1\130\1\0\14\103\1\110\7\103\1\0\2\103"+
    "\4\0\6\127\1\130\1\131\1\127\1\130\2\127\1\132"+
    "\1\103\1\130\1\0\13\103\1\111\10\103\1\0\2\103"+
    "\4\0\6\127\1\130\1\131\1\127\1\130\2\127\1\132"+
    "\1\103\1\130\1\0\10\103\1\112\13\103\1\0\2\103"+
    "\4\0\6\127\1\130\1\131\1\127\1\130\2\127\1\132"+
    "\1\103\1\130\1\0\4\103\1\113\17\103\1\0\2\103"+
    "\4\0\6\127\1\130\1\131\1\127\1\130\2\127\1\132"+
    "\1\103\1\130\1\0\16\103\1\114\5\103\1\0\2\103"+
    "\4\0\6\127\1\156\1\132\1\127\1\156\3\127\2\156"+
    "\1\0\24\156\1\0\2\156\4\0\5\127\4\135\1\157"+
    "\1\135\4\127\1\0\24\127\1\0\1\127\1\157\4\0"+
    "\5\127\1\135\1\136\1\137\1\135\1\115\1\135\1\127"+
    "\1\132\1\103\1\130\1\0\24\103\1\0\1\103\1\115"+
    "\15\0\1\163\3\0\1\163\2\0\24\163\1\0\2\163"+
    "\7\0\1\25\1\26\1\0\1\27\1\41\1\0\1\22"+
    "\1\164\1\0\1\21\1\22\1\23\1\26\17\22\1\31"+
    "\4\22\1\0\2\22\12\0\1\163\1\165\1\0\1\163"+
    "\3\0\2\163\1\0\24\163\1\0\2\163\15\0\1\166"+
    "\3\0\1\166\2\0\24\166\1\0\2\166\15\0\1\163"+
    "\3\0\1\167\2\0\24\167\1\0\2\167\12\0\1\166"+
    "\1\164\1\0\1\166\2\0\1\21\2\166\1\0\24\166"+
    "\1\0\2\166\12\0\1\163\1\165\1\0\1\163\3\0"+
    "\1\127\1\163\1\0\24\127\1\0\2\127\1\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[4859];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\1\11\6\1\2\0\1\1\2\0"+
    "\3\1\2\0\10\1\1\11\1\1\1\0\54\1\2\0"+
    "\1\1\1\0\1\1\1\0\15\1\1\0\17\1\1\0"+
    "\1\1\5\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[119];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
	public final int yychar()
	{
	    return Math.toIntExact(yychar);
	}
    /**
     * Return the internal token's character buffer.
     */
	final char [] yybuffer() {
		return zzBuffer;
	}

	final int yystart() {
		return zzStartRead;
	}


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public ExtendedWhitespaceTokenizerImpl(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public int getNextToken() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { /* ignorable . */ break;
            }
          // fall through
          case 13: break;
          case 2:
            { return Tokenizer.TT_PUNCTUATION | Tokenizer.TF_SEPARATOR_SENTENCE;
            }
          // fall through
          case 14: break;
          case 3:
            { return Tokenizer.TT_PUNCTUATION;
            }
          // fall through
          case 15: break;
          case 4:
            { return Tokenizer.TT_NUMERIC;
            }
          // fall through
          case 16: break;
          case 5:
            { return Tokenizer.TT_TERM;
            }
          // fall through
          case 17: break;
          case 6:
            { return Tokenizer.TT_FILE;
            }
          // fall through
          case 18: break;
          case 7:
            { /* html entities. */ break;
            }
          // fall through
          case 19: break;
          case 8:
            { return Tokenizer.TT_EMAIL;
            }
          // fall through
          case 20: break;
          case 9:
            { return Tokenizer.TT_ACRONYM;
            }
          // fall through
          case 21: break;
          case 10:
            { return Tokenizer.TT_HYPHTERM;
            }
          // fall through
          case 22: break;
          case 11:
            { return Tokenizer.TT_BARE_URL;
            }
          // fall through
          case 23: break;
          case 12:
            { return Tokenizer.TT_FULL_URL;
            }
          // fall through
          case 24: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
