name: On Commit Checks

on: 
  pull_request:
    branches:
      - master

  push:
    branches:
      - master
      - bugfix/4.4.x

jobs:
  tests:
    name: gradle check (JDK ${{ matrix.java }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      # Check on latest ubuntu with the lowest supported JDK. Everything else
      # is handled by subsequent nightly tests.
      matrix:
        os: [ ubuntu-latest ]
        java: [ '11' ]

    steps:
      - name: Correct git autocrlf
        run: git config --global core.autocrlf false

      - name: Git checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          java-package: jdk

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Quick checks (gradle check -x test)
        run: ./gradlew --max-workers 4 check -x test

      - name: Tests (./gradlew ... check)
        run: ./gradlew --max-workers 4 check

      - name: Store failed test outputs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: failed-test-outputs
          path: '**/OUTPUT-*.txt'

      - name: Archive distribution artifacts
        uses: actions/upload-artifact@v4
        with:
          name: distribution
          path: |
            distribution/build/distZip/*.zip
